export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const SELECT_EMPLOYEE = "SELECT_EMPLOYEE";
export const CLEAR_EMPLOYEE = "CLEAR_EMPLOYEE";
export const DELETE_SELECTED_EMPLOYEE = "DELETE_SELECTED_EMPLOYEE";
